### ISSUE TITLE
Review from guides team

### ISSUE THREAD

**Issue by Kubik42** [cthigh/guide-grade-intro#4]
**header**

- [x] 30 minutes is probably too long for this guide. Perhaps 15 minutes just like the Maven intro one?
- [x] missing a source highlighter -> `:source-highlighter: prettify`

**What you’ll learn**
- [x] can you add some transitions into the first paragraph? Its a bit awkward going from "You will learn..." to "The war plugin..."

**Creating the application**
- [x] remove the extra indent from the snippet

**Installing Gradle**
- [x] "Now you’re ready to install Gradle if you don’t already have version 3 or higher. " -> perhaps change this sentence to something like "If you don't have Gradle installed, follow the Gradle installation page" or something like that. The sentence as is, feels like its missing punctuation

**Configure your project**
- [x] avoid using "we" (ex. "We will go through creating ...", etc.) -> its something the ID team wanted us to do as well for the other guides
- [x] instead of explaining where to create a specific file; ex. "First, create a settings.gradle file in the current directory where you cloned..." can you add something like "Create <path to file>:" before every snippet? This is much easier to follow imo
- [x] "Let’s go through the parts of the build.gradle file so that you understand each part." -> change this bullet point list to a table instead
- [x] " because Liberty provides the ...", "but since Liberty provides..." -> should be Open Liberty
- [x] can you update the open liberty version to be 17.0.0.3 in the build file instead of 17.0.0.2?
- [x] "Other versions of the WebSphere Liberty runtime are also available in Maven Central." -> are these regular liberty runtime? If so, we shouldn't mention them since this guide is for Open Liberty
- [x] "we configure the Liberty server including:" -> replace the bullets with a table
- [x] can you be more clear what needs to be copied into the gradle build file? Personally, I like to say something like "Put <this> into <that> file:" and add the code snippet underneath. Ex. you can say "Add the `repositories` section to your build file:" and then add that code snippet underneath.
- [x] extra indents on the last two snippets in this section

**Testing**
- [x] (I see that this class was copied from the Maven intro guide, so it has the same issues) - the test class "EndpointIT.java" has a lot of extra space, which needs to be cleaned up. The "testServlet" method also probably doesn't need both a try/catch block and a throws declaration
- [x] (same as Maven intro class) I would change "statusCode" to "actualStatusCode" and then define a new variable called "int expectedStatusCode = HttpStatus.SC_OK". This way its clear what is the expected and what is the actual result.
- [x] (same as Maven intro class) perhaps change "method" to "getMethod"?
- [x] "The directory structure of the project should now look like this:" -> extra indent in this snippet
- [x] "You can now run the command gradle build -i" -> add from what directory this command should be executed

I'm not really familiar with gradle, but shouldn't the last bit of the build file (ie. "clean.dependsOn 'libertyStop' and so on") be added in before running the build? If so, you need to mention it somewhere before "You can now run the command gradle build -i to build the application and test the application"

**Comment by cthigh** [comment]
The testServlet class has a try/finally to release the connection - not a try/catch.

Opted for `client` to change to `httpClient` and `method` to change to `httpGetMethod`.

**Comment by cthigh** [comment]
I have merged the requested updates.
