### ISSUE TITLE
Change focus from root to "start" directory

### ISSUE THREAD

**Issue by Kubik42** [cthigh/guide-grade-intro#6]
- [x] I think “because Open Liberty provides the implementation at run time” should be “because Open Liberty provides *their* implementation at run time”
- [x] “rather than repackaging your WAR file to see application updates live on the server” should be “rather than *repackage* your *entire* WAR file to see application updates live on the server”
- [x] "include::finish/src/test/java/io/openliberty/guides/hello/it/EndpointIT.java[tags=*;!comment]" should have a double asterisk otherwise most of the test class doesn't render
- [x] "Thia configures Gradle to run the integration tests in the */it/** folder." -> typo: "Thia"
- [x] the code snippet below "The following lines in the `EndpointIT.java` test class uses these system variables to build the URL of the application:" is marked as XML instead of Java, so its missing highlighting.
- [x] same as above point but for the snippet below "The HTTP client then disconnects from the application."
- [x] I would change "The complete build.gradle file should now look like this example:" to instead say "The complete build.gradle file should now look like the following:"

**Comment by cthigh** [comment]
fixed these and the start directory issues.
